### ISSUE TITLE
CI가 모든 경로에 의해 반응되고 있습니다.

### ISSUE THREAD

**Issue by KimKyuHoi** [sgdevcamp2025/c_sharp#78]
### Summary

![Image](https://github.com/user-attachments/assets/3920dbf9-baa5-447c-9750-03043a71bea2)

- 현재 FE내에서도 백엔드 CI가 돌고 있습니다. 

### Expected behavior

- BE내에서 CI를 처리를 해주실 때 src/backend라는 따로 경로를 처리해주지 않기 때문에 FE내에서 일반 PR을 올리게 되었을때 현재 모든 CI가 발생하게 됩니다.

### Actual behavior

![Image](https://github.com/user-attachments/assets/3618979f-920f-4ed4-a156-5b2637c3f041)

### Steps to reproduce the problem

- 일반 PR을 올리게 될경우

### Environment

- Version: Apple M2 macOs 16gb 512gb Sequioa ver15.2

### Possible fix

@mirlee0304 

**FE에서 CI를 돌릴 경우**

```yml
name: FRONTEND-CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main
    paths:
      - 'src/frontend/**'
```

프론트엔드에서 CI를 돌아가게되는경우 ```paths: 'src/frontend/**'```의 trigger를 걸어 frontend내에 변화가 일어나게 되었을 경우에만 CI가 발생하도록 합니다.

**BE에서 CI를 돌릴 경우**
```yml
name: CI Pipeline for Jutalkpia

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
```

백엔드에서 CI를 돌리게 될 경우 일반적인 경로가 조정이 되어있지 않기 때문에 전 PR전부 다 발생하게 됩니다. 이것 관련하여 확인이 필요합니다.
또한 Pull Request내에서 이렇게 될 경우 한번만 CI가 돌아갈 경우가 있습니다. 이때 오류가 발생하게 될 경우 CI가 다시 안 돌아갈 수 도 있기 때문에

pull_request내에 types를 지정하여 [opened, sychronize, reopenend]를 제안합니다.
